import networkx as nx

G=nx.DiGraph()

G.add_node(1)
G.add_node(2)
G.add_node(3)
G.add_node(4)
G.add_node(5)
G.add_node(6)
G.add_node(7)
G.add_node(8)
G.add_node(9)
G.add_node(10)
G.add_node(11)
G.add_node(12)
G.add_node(13)
G.add_node(14)
G.add_node(15)

G.add_edge(1, 2)
G.add_edge(1, 3)
G.add_edge(1, 4)
G.add_edge(1, 5)
G.add_edge(1, 6)
G.add_edge(1, 7)
G.add_edge(1, 8)
G.add_edge(1, 9)
G.add_edge(1, 10)
G.add_edge(1, 11)
G.add_edge(1, 12)
G.add_edge(1, 13)
G.add_edge(1, 14)
G.add_edge(1, 15)

G.add_edge(2, 3)
G.add_edge(3, 4)
G.add_edge(4, 5)
G.add_edge(5, 6)
G.add_edge(6, 7)
G.add_edge(7, 8)
G.add_edge(8, 9)
G.add_edge(9, 10)
G.add_edge(10, 11)
G.add_edge(11, 12)
G.add_edge(12, 13)
G.add_edge(13, 14)
G.add_edge(14, 15)
G.add_edge(15, 2)

nx.draw(G,with_labels=True)

print("Número de Aristas: " + str(G.number_of_edges()))
print("Número de Nodos: " + str(G.number_of_nodes()))
print("Tamaño: " + str(G.size()))
print("Orden: " + str(G.order()))